### PR TITLE
Tutorial fixes

### LINKED ISSUE #141: Add note in tutorial that -P is required for lumpy
You have to run lumpy with -P in order to get the probability curves output to the vcf.  lmerge needs these in the info field

### LINKED ISSUE #142: Remove bsub commands from tutorial
It's confusing if you don't have LSF.

### PR DESCRIPTION
**Pull request by ernfrid**
These are intended to resolve #142 and resolve #141. @apregier - can you take a look and tell me if you think these changes do the trick?

### CODE REVIEW

**Comment by apregier** [comment]
The genotype step is also one where quoting for bsub was removed, but the escapes weren't

**Comment by ernfrid** [comment]
Better?

**Comment by apregier** [comment]
+1

**Comment by ernfrid** [comment]
Thanks!

**Pull request merged**
