### PR TITLE
flip pos, END where needed

### PR DESCRIPTION
**Pull request by brentp**
see brentp/smoove#56

### CODE REVIEW

**Comment by brentp** [comment]
ping

**Comment by WimSpee** [comment]
ping

**Comment by brentp** [comment]
hi @ernfrid, would be nice to get this in. anything else needed?

**Comment by ernfrid** [comment]
Sorry @brentp. I've just been fully occupied with the new job and not paying much attention to svtools.

The test does need to be fixed. We must have had a few examples of this in the lmerge output.

I think @apregier is preparing a new release, maybe this can be part of that.

**Comment by apregier** [comment]
Yes, hoping to do a release next Wednesday when I get back from vacation, if you can get the test fixed before then I will make sure it gets in.

**Comment by apregier** [comment]
Hi @brentp I just took a look at the failing tests - it looks like the change is causing havoc for interchromosomal BNDs - probably need to add a check to not swap unless breakpoints are on the same chrom.

**Comment by apregier** [comment]
+1

**Pull request merged**
